### ISSUE TITLE
"mood" playlists aren't loading

### ISSUE THREAD

**Issue by Kaezoo26** [knighthat/Kreate#326]
### Version of Kreate

1.3.4 fdroid

### Android version

15 [VANILLA_ICE_CREAM]

### TODOs before submitting a ticket

- [x] Update my app to latest version (see link below)
- [x] (If I'm on latest version) Re-install app
- [x] I have checked issue page and there's no problem like mine

### Tell us how to trigger this bug

1. Open Kreate
2.Issue : "Mood" playlists aren't loading. Is there an option for this? I've checked the settings. Thanks. 

![Image](https://github.com/user-attachments/assets/e33f347b-13f3-490d-8b9c-9a5cfad9825e)

### What was your expectation?

I want this "mood" playlists 😁

### Logs (Optional)

<details>
  <summary>Logs</summary>
  [If you have multiple logs, please copy "details" for each log, name them appropriately, make sure they are different from each other]
  <Paste your log here>
</details>

**Comment by knighthat** [comment]
should be fixed in next release

**Comment by knighthat** [comment]
:tada: This issue has now been fixed and is available in [v1.4.2](https://github.com/knighthat/Kreate/releases/tag/v1.4.2) :tada:
This ticket is now closed. If you have any more question, feel free to reply below. If needed, the ticket will be re-open for further support.

**Comment by Itchyfantastico** [comment]
I just installed 1.4.2 from F-Droid and the playlists are still not loading unfortunately.

**Comment by knighthat** [comment]
are you using any language other than EN?
