### ISSUE TITLE
Notification player doesn't update color

### ISSUE THREAD

**Issue by MedieroAF** [knighthat/Kreate#517]
### Version of Kreate

v1.6.2

### Android version

15 [VANILLA_ICE_CREAM]

### TODOs before submitting a ticket

- [x] Update my app to latest version (see link below)
- [x] (If I'm on latest version) Re-install app
- [x] I have checked issue page and there's no problem like mine

### Tell us how to trigger this bug

Theme and theme mode are set to "dynamic", which is how they were set until (last update?). I didn't really change any settings at all and the notification just stopped showing the correct color.

### Submit a video

![Image](https://github.com/user-attachments/assets/8a7c08c5-423f-4687-b2de-7d944ac48fb0)

### What was your expectation?

For the provided example although I don't have a screenshot of how it should look, the background of the notification should look yellowish with a slight gradient, but instead it looks almost black. This dark gray doesn't change even if the in-app theme changes to other colors.

**Comment by knighthat** [comment]
is the color applied to the in-app UI?

**Comment by MedieroAF** [comment]
Yes. Additionally, the app color isn't the same as the notification color, since with that album for example the app looks orange.

**Comment by knighthat** [comment]
The most noticeable color in a picture is used as the theme color. In this case, it's orange

Secondly, I don't think the app has a built-in feature to modify it. Hell, I don't even think it's available for devs to do so.

Also, you can change notification type in setting, trying changing them to another value.

Regardless, I'll look into this and lyk later

**Comment by MedieroAF** [comment]
Damn, then it might be an Android built-in feature.

I have notification setting on "advanced" and I tried setting it to "Default" and reloading but that didn't work, neither did putting it on "Advanced" again. Really baffled at why it broke since it was overnight, I don't even think there was an update in between

**Comment by knighthat** [comment]
Is it only happen to Kreate or other media players to?

**Comment by MedieroAF** [comment]
Now that you mention it, I'm starting to think it's system-based. I'm going to look into it and see if I can fix anything from my phone. Sorry for the bother.

**Comment by knighthat** [comment]
No problem! Let's see if it's system-wide or just Kreate. I'll keep the ticket up for now

**Comment by knighthat** [comment]
I updated parts related to media control. Let's see if problem persists

**Comment by MedieroAF** [comment]
Nothing. Might be system-related, but I can't find a fix. Maybe it just gets fixed with the next system update.

Thanks for your time (and for remembering this issue after a while!)

**Comment by knighthat** [comment]
I'm trying to figure out whether the problem is from Kreate. I'll notify you if something changes so you can further test it

**Comment by knighthat** [comment]
I still don't know why it's like this on your phone. Afaik, this is pretty isolated, so I will close this ticket
